branches:
  - name: master
    prerelease: false
  - name: main
    prerelease: false
  - name: develop
    prerelease: true


plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'