# .releaserc file
# Configure the semantic-release workflow used to automatically tag / release on commits to certain branches

branches:

  - name: main
    prerelease: false

  - name: develop
    prerelease: true

# Plugins; Omit the npm plugin entirely, as we are not publishing on npm
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'