name: Deploy Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - 'wiki/**'
    branches: [ main ]

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
