name: Deploy Wiki

on:
  workflow_dispatch:
  push:
    # Trigger only when wiki directory changes
    # paths:
      #- 'wiki/pages/**'

    # Trigger only on main
    branches: [ main, develop ]

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tools to build whl package
      run: |
        pip install sdist

    - name: Build whl package
      run: |
        python setup.py sdist bdist_wheel
      env:
        SEMANTIC_VERSION: 1.0.0   # not actually 1.0.0, but has no impact on wiki-building

    - name: Install do-calculus package
      run: |
        pip install -e .

    - name: Build Pages (replace stubs)
      run: |
        python ./wiki/build_wiki.py

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: wiki/pages/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
