name: Deploy Wiki

on:
  push:
    # Trigger only when wiki directory changes
    paths:
      - 'doc/**'

    # Trigger only on main
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: doc/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.GITHUB_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
